apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  namespace: default
  name: marketplace
spec:
  sources:
    - match:
        kuma.io/service: 'frontend_kuma-demo_svc_8080'
    - match:
        kuma.io/service: 'postgres_kuma-demo_svc_5432'
    - match:
        kuma.io/service: 'redis_kuma-demo_svc_6379'
    - match:
        kuma.io/service: 'backend_kuma-demo_svc_3001'
  destinations:
    - match:
        kuma.io/service: 'frontend_kuma-demo_svc_8080'
    - match:
        kuma.io/service: 'postgres_kuma-demo_svc_5432'
    - match:
        kuma.io/service: 'redis_kuma-demo_svc_6379'
    - match:
        kuma.io/service: 'backend_kuma-demo_svc_3001'
