apiVersion: kuma.io/v1alpha1
kind: HealthCheck
metadata:
  name: frontend-to-backend
  namespace: kuma-demo
mesh: default
spec:
  sources:
  - match:
      kuma.io/service: frontend_kong-mesh-demo_svc_8080
  destinations:
  - match:
      kuma.io/service: backend_kong-mesh-demo_svc_3001
  conf:
    interval: 10s
    timeout: 2s
    unhealthyThreshold: 3
    healthyThreshold: 1
    tcp:
      send: Zm9v
      receive:
      - YmFy
      - YmF6
    http:
      path: /health
      requestHeadersToAdd:
      - append: false
        header:
          key: Content-Type
          value: application/json
      - header:
          key: Accept
          value: application/json
      expectedStatuses: [200, 201]
