apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: api-split
spec:
  sources:
    - match:
        kuma.io/service: frontend_kuma-demo_svc_8080
  destinations:
    - match:
        kuma.io/service: backend_kuma-demo_svc_3001
  conf:
    http:
    - match:
        path:
          regex: ".*"
      split:
      - weight: 90
        destination:
          kuma.io/service: backend_kuma-demo_svc_3001
          version: 'v0'
      - weight: 10
        destination:
          kuma.io/service: backend_kuma-demo_svc_3001
          version: 'v1'
    destination: # default rule is applied when endpoint does not match any rules in http section
      kuma.io/service: backend_kuma-demo_svc_3001
      version: 'v1'
